### PR TITLE
[gke-disk-image-builder] Set device name explicitly in startup.sh

### LINKED ISSUE #124: gke-disk-image-builder does not work with hyperdisks
When attempting to use the gke-disk-image-builder tool with hyperdisk, we ran into the following error:

`Nov 22 22:58:32 debian google_metadata_script_runner[2040]: startup-script-url: Device /dev/sdb does not exist. Please rerun the tool to try it again.`

**Steps to Reproduce**:

`go run ./cli --project-name=$PROJECT_NAME --image-name=triton-2309-py3-hd --zone=$ZONE --gcs-path=gs://$GCS_PATH/ --container-image='nvcr.io/nvidia/tritonserver:23.09-py3' --machine-type=h3-standard-88 --disk-type=hyperdisk-balanced`

### PR DESCRIPTION
**Pull request by danielvegamyhre**
Fixes #124 

Evidently, the device node for hyperdisks is in not in the same location in the filesystem as other disk types (1st one /dev/sdb, 2nd one /dev/sdc, and so on). 

To fix this, we can use the device name explicitly: `/dev/disk/by-id/google-<device name>` (for non-partitioned disks) and `/dev/disk/by-id/google-<device name>-part1` (for partitioned disks).

The changes in this PR use the device name explicitly, as defined [here](https://github.com/GoogleCloudPlatform/ai-on-gke/blob/71ebab897948cbca722c9abf4ec3ff2bc1318b3b/gke-disk-image-builder/imager.go#L111).

I tested these changes manually with the following command and it worked:

`go run ./cli --project-name=$PROJECT_NAME --image-name=triton-2309-py3-hd --zone=$ZONE --gcs-path=gs://$GCS_PATH/ --container-image='nvcr.io/nvidia/tritonserver:23.09-py3' --machine-type=h3-standard-88 --disk-type=hyperdisk-balanced`

### CODE REVIEW

File: gke-disk-image-builder/script/startup.sh [hunk 1]
```diff
@@ -27,16 +27,23 @@ else
...
+DEVICE_NODE=/dev/disk/by-id/google-secondary-disk-image-disk
+if [[ -e "$DEVICE_NODE-part1" ]]; then
+  DEVICE_NODE="$DEVICE_NODE-part1"
+fi
+echo "using device node: $DEVICE_NODE"
+
 # Check if the device exists
-if ! [ -b /dev/sdb ]; then
-  echo Device /dev/sdb does not exist. Please rerun the tool to try it again.
+if ! [ -b /dev/disk/by-id/google-secondary-disk-image-disk ]; then
```
Comment (ruiwen-zhao) [inline gke-disk-image-builder/script/startup.sh:38]: should we use `$DEVICE_NODE` instead of the absolute path (same below)?

File: gke-disk-image-builder/script/startup.sh [hunk 2]
```diff
@@ -27,16 +27,23 @@ else
   exit 1
 fi
 
+# Check if disk is partitioned and update disk path accordingly if so.
+DEVICE_NODE=/dev/disk/by-id/google-secondary-disk-image-disk
```
Comment (samuelkarp) [inline gke-disk-image-builder/script/startup.sh:31]: nit: mind adding a comment pointing to the line that defines this name?

**Review by samuelkarp — APPROVED** [review]

File: gke-disk-image-builder/script/startup.sh (hunk 1 above)
Comment (danielvegamyhre) [reply gke-disk-image-builder/script/startup.sh]: thanks, i actually had this locally already but forgot to push the changes! done.

**Review by ruiwen-zhao — APPROVED** [review]
